### ISSUE TITLE
Issues following along with coding on Replit

### ISSUE THREAD

**Issue by CarynEB** [learn-co-curriculum/phase-0-pac-1-working-with-strings#2]
### Canvas Link

https://learning.flatironschool.com/courses/5282/pages/working-with-strings?module_item_id=349428

### Concern

I tried multiple times to follow along on replit but I received a command not found. I don't know if I need to install anything on that site but I opened up two templates for Java and couldn't do the strings. 
![Replit errors](https://user-images.githubusercontent.com/101961338/159207360-c0db84e1-5116-439a-b2a2-aaf87fa0e0c4.PNG)

### Suggested Changes

Could someone contact me to advise on how to fix the issue?

**Comment by lizbur10** [comment]
Hi @CarynEB ! It looks like you may be in the Java environment rather than JavaScript. Be sure to go to this URL: https://replit.com/languages/javascript 

If you continue to have difficulties, you might want to reach out to [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) to get help.

**Comment by CarynEB** [comment]
Nothing is appearing on the console. I am having issues because I am typing in code blindly without seeing results. I really need help, please.
________________________________

**Comment by lizbur10** [comment]
Hi @CarynEB - we are not able to provide support. Please reach out to [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) to get help.
